### PR TITLE
try to update ubuntu version for newer gcc

### PR DESCRIPTION
**Pull request by MOON-CLJ**

### CODE REVIEW

**Comment by tclh123** [comment]
Maybe install `g++-7` and don't modify other things such as `CMakeLists.txt`.

**Comment by MOON-CLJ** [comment]
@tclh123 also add CMAKE_C_COMPILER CMAKE_CXX_COMPILER in CMakeLists.txt is because cmake build gtest seems like not use CC and CXX，see https://travis-ci.org/douban/libmc/jobs/483223951。

"""
-- The C compiler identification is Clang 5.0.0
-- The CXX compiler identification is Clang 5.0.0
"""

"""
In file included from /home/travis/build/douban/libmc/build/googletest-src/googletest/include/gtest/internal/gtest-port.h:253:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:35:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/c++0x_warning.h:32:2: error: 
"""

**Comment by MOON-CLJ** [comment]
@tclh123 take a look https://docs.travis-ci.com/user/build-matrix/， i dont use "matrix:\n  include" way to specific gcc version as https://docs.travis-ci.com/user/languages/cpp/#c11c11-and-beyond-and-toolchain-versioning 's suggestion，because i dont distinguish how to combine "matrix: \n include" (include only) and normal matrix。

**Comment by MOON-CLJ** [comment]
> i dont distinguish how to combine "matrix: \n include" (include only) and normal matrix。

i dont distinguish how to build matrix to contain following dimensions instead of use "matrix: \n include" explicitly list every combination one by one 。

1, use "matrix: \n include" to specific clang & gcc version
2, two python version 
3，env release and debug

**Comment by tclh123** [comment]
@MOON-CLJ https://github.com/douban/libmc/pull/91 lgty?

**Pull request closed without merging**
