### PR TITLE
Use connection pool in golibmc

### PR DESCRIPTION
**Pull request by jumpeiMano**
https://github.com/douban/libmc/issues/36

I'm using golibmc with some products.

I tried implementing the connection pool for golibmc.
Excuse me for being busy, but I'd appreciate it if you can check this PR.

By the way, there is something I want to ask a question.The build of Travis CI always fails, because of these errors from Cppcheck.
```
Checking usage of global functions..

[src/Client.cpp:215]: (style) The function '_sleep' is never used.

[src/c_client.cpp:90]: (style) The function 'client_add' is never used.

[src/c_client.cpp:92]: (style) The function 'client_append' is never used.

[src/c_client.cpp:94]: (style) The function 'client_cas' is never used.

[src/c_client.cpp:25]: (style) The function 'client_config' is never used.

[src/c_client.cpp:8]: (style) The function 'client_create' is never used.

[src/c_client.cpp:128]: (style) The function 'client_decr' is never used.

[src/c_client.cpp:112]: (style) The function 'client_delete' is never used.

[src/c_client.cpp:31]: (style) The function 'client_destroy' is never used.

[src/c_client.cpp:56]: (style) The function 'client_destroy_broadcast_result' is never used.

[src/c_client.cpp:106]: (style) The function 'client_destroy_message_result' is never used.

[src/c_client.cpp:72]: (style) The function 'client_destroy_retrieval_result' is never used.

[src/c_client.cpp:135]: (style) The function 'client_destroy_unsigned_result' is never used.

[src/c_client.cpp:67]: (style) The function 'client_get' is never used.

[src/c_client.cpp:68]: (style) The function 'client_gets' is never used.

[src/c_client.cpp:120]: (style) The function 'client_incr' is never used.

[src/c_client.cpp:13]: (style) The function 'client_init' is never used.

[src/c_client.cpp:93]: (style) The function 'client_prepend' is never used.

[src/c_client.cpp:145]: (style) The function 'client_quit' is never used.

[src/c_client.cpp:91]: (style) The function 'client_replace' is never used.

[src/c_client.cpp:89]: (style) The function 'client_set' is never used.

[src/c_client.cpp:140]: (style) The function 'client_stats' is never used.

[src/c_client.cpp:98]: (style) The function 'client_touch' is never used.

[src/c_client.cpp:50]: (style) The function 'client_version' is never used.

[src/Utility.cpp:43]: (style) The function 'fprintBuffer' is never used.

(information) Cppcheck cannot find all the include files (use --check-config for details)
```
Do you have any ideas to fix them?
https://travis-ci.org/jumpeiMano/libmc/jobs/297054286

Thanks!

### CODE REVIEW

**Comment by mckelvin** [comment]
Hey @jumpeiMano , Thanks for your PR. Before start reviewing your PR, I'll help you resolve the cppcheck issue first. The reason why it fails may because cppcheck of different versions between your branch and the master branch.

Your branch:

```
 of Get:3 http://archive.ubuntu.com/ubuntu trusty/universe amd64 cppcheck amd64 1.61-1 [684 kB]
```

The master:

```
Get:3 http://us-central1.gce.archive.ubuntu.com/ubuntu precise/universe amd64 cppcheck amd64 1.52-1 [569 kB]
```

I tried to clean the cache on Travis-CI but it doesn't work. Anyway, I'll fix the issue in a separate PR.

**Comment by mckelvin** [comment]
Hi @jumpeiMano , Would you please rebase with the latest code in master branch? The CI issue should be resolved now.

**Comment by jumpeiMano** [comment]
Thanks for your response!!

Oh......!
I made a mistake in rebasing work ... I will create another pull request again...sorry...

**Comment by jumpeiMano** [comment]
Please check [this PR](https://github.com/douban/libmc/pull/57)...!

**Pull request closed without merging**
