### PR TITLE
golibmc: DeleteMulti applying for prefix

### PR DESCRIPTION
**Pull request by mosasiru**
golibmc DeleteMuti doesn't work when prefix is set.
so I fixed it.

### CODE REVIEW

**Comment by youngsofun** [comment]
@mosasiru  thanks a lot

should we **replace** all newSimpleClient with newSimplePrefixClient? @mckelvin

**Comment by mckelvin** [comment]
Nice shot! Thanks so much, @mosasiru .I've checked other functions and found the bug is only existed in `DeleteMulti`. Thanks again for pointing that out.

@youngsofun If you mean in `golibmc_test.go`, Agree. We should better so to improve the coverage for the prefix-feature which used in all functions including Get/Set/Delete and their corresponding functions.

### LGTM

**Comment by mckelvin** [comment]
@mosasiru A new version of libmc ( v1.0.1 ) was just released. Now you can use the code in upstream.

**Comment by mosasiru** [comment]
thank you very much!

**Pull request merged**
