### PR TITLE
Feature/fix symlink

### PR DESCRIPTION
**Pull request by ntkm**
Hi, I'm using golibmc.
I realized dead link of subpackage(golibmc) and fixed it.
This is trivial change.

### CODE REVIEW

**Comment by ntkm** [comment]
> `E: Package 'libmemcached6' has no installation candidate`

oh....

**Comment by ntkm** [comment]
I'm not Contributer. So, reverted `bump up version`.

**Comment by ntkm** [comment]
I was importing: `"github.com/douban/libmc/golibmc"`
However,`cd golibmc` in  in https://github.com/douban/libmc/blob/master/misc/travis/unittest.sh#L18
failed.
I think my importing was wrong.

**Comment by ntkm** [comment]
> I think my importing was wrong.

I tried this... But I have to modify several packages... It's large cost.
Not a few developers run into same problem, I think.
So, merging this will make developers happy, I blieave.
Please consider

**Comment by mckelvin** [comment]
Hey @ntkm , What do you mean by "dead link" ?The symbolic link looks work well.

```
$ ls -al golibmc
lrwxr-xr-x  1 kelvin  staff  3 Jun 28  2016 golibmc -> src

$ ls golibmc
BufferReader.cpp   Common.cpp         DataBlock.cpp      HashkitKetama.cpp  Result.cpp         golibmc.go
BufferWriter.cpp   Connection.cpp     HashkitCrc.cpp     HashkitMd5.cpp     Utility.cpp        golibmc_test.go
Client.cpp         ConnectionPool.cpp HashkitFnv.cpp     Parser.cpp         c_client.cpp       version.go
```

You should be able to use libmc like this:

```go
package main

import "fmt"
import "github.com/douban/libmc/golibmc"

func main() {
	servers := []string{
		"localhost:11211",
	}
	key := "foo"
	mc := golibmc.SimpleNew(servers)
	item := golibmc.Item{
		Key:   key,
		Value: []byte("year2016"),
	}
	mc.Set(&item)
	itemGot, _ := mc.Get(key)
	fmt.Println(string(itemGot.Value))
}
```

Would you please provide a minimal example to reproduce the issue you trying to resolve?
Thanks.

**Comment by ntkm** [comment]
Hi @mckelvin, Thx for your locking.
When do `dep init` (for migrating glide to dep), missing subpackage( `github.com/douban/libmc/golibmc` )
```
No versions of github.com/douban/libmc met constraints:
	master: Could not introduce github.com/douban/libmc@master, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v1.1.0: Could not introduce github.com/douban/libmc@v1.1.0, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v1.0.1: Could not introduce github.com/douban/libmc@v1.0.1, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v1.0.0: Could not introduce github.com/douban/libmc@v1.0.0, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.6: Could not introduce github.com/douban/libmc@v0.5.6, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.5: Could not introduce github.com/douban/libmc@v0.5.5, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.4: Could not introduce github.com/douban/libmc@v0.5.4, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.3: Could not introduce github.com/douban/libmc@v0.5.3, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.2: Could not introduce github.com/douban/libmc@v0.5.2, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.1: Could not introduce github.com/douban/libmc@v0.5.1, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	v0.5.0: Could not introduce github.com/douban/libmc@v0.5.0, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
	stable: Could not introduce github.com/douban/libmc@stable, as its subpackage github.com/douban/libmc/golibmc is missing. (Package is required by (root).)
```
So, I tried to resolve this by changing symlink target.

**Comment by everpcpc** [comment]
https://github.com/golang/dep/pull/1531

**Comment by ntkm** [comment]
Hi @everpcpc 

Thank you! I'll try it!

**Comment by ntkm** [comment]
I realized that I cannot import symlinked path...

**Pull request closed without merging**
